/*

Script Purpose:
	Inserting bronze.daily_stg data into silver layer with constraints for idempotency.

Note:
	Incremental logic ensures only one forecast per mountain per calendar day (e.g. '2025-12-25'). 
	If the pipeline runs multiple times on the same day, existing records are 
	updated rather than duplicated.

	latitude, longitude, elevation_m(ft), and timezone are mountain-level attributes
	stored in silver.mountains and are not repeated here (3NF).

*/

insert into silver.daily (
    daily_id,
    mountain_id, 
    measured_at, 
    create_date, 
    forecast_date, 
    sunset, 
    sunrise,
    weather_code, 
    rain_sum_mm, 
    showers_sum_mm,
    snowfall_sum_cm,
    uv_index_max, 
    visibility_max_m,
    visibility_min_m, 
    visibility_mean_m,
    cloud_cover_max_pct, 
    cloud_cover_min_pct, 
    cloud_cover_mean_pct,
    dew_point_2m_max_celsius,
    dew_point_2m_min_celsius, 
    dew_point_2m_mean_celsius,
    daylight_duration_seconds,
    precipitation_sum_mm,
    precipitation_hours,
    precipitation_probability_max_pct, 
    precipitation_probability_min_pct,
    precipitation_probability_mean_pct,
    sunshine_duration_seconds, 
    temperature_2m_max_celsius, 
    temperature_2m_min_celsius,
    temperature_2m_mean_celsius, 
    apparent_temperature_max_celsius, 
    apparent_temperature_min_celsius,
    apparent_temperature_mean_celsius,
    wind_gusts_10m_max_kmh,
    wind_gusts_10m_min_kmh,
    wind_gusts_10m_mean_kmh, 
    wind_speed_10m_max_kmh, 
    wind_speed_10m_min_kmh,
    wind_speed_10m_mean_kmh,
    wind_direction_10m_dominant,
    surface_pressure_max_hpa, 
    surface_pressure_min_hpa, 
    surface_pressure_mean_hpa,
    relative_humidity_2m_max_pct, 
    relative_humidity_2m_min_pct, 
    relative_humidity_2m_mean_pct
)
select distinct on (mountain_id, (daily_json -> 'daily' -> 'time' ->> idx)::date)
    daily_id,
    mountain_id,
    measured_at,
    create_date,
    (daily_json -> 'daily' -> 'time'                        ->> idx)::date          as forecast_date,
    (daily_json -> 'daily' -> 'sunset'                      ->> idx)::timestamptz   as sunset,
    (daily_json -> 'daily' -> 'sunrise'                     ->> idx)::timestamptz   as sunrise,
    (daily_json -> 'daily' -> 'weather_code'                ->> idx)::int           as weather_code,
    (daily_json -> 'daily' -> 'rain_sum'                    ->> idx)::numeric       as rain_sum_mm,
    (daily_json -> 'daily' -> 'showers_sum'                 ->> idx)::numeric       as showers_sum_mm,
    (daily_json -> 'daily' -> 'snowfall_sum'                ->> idx)::numeric       as snowfall_sum_cm,
    (daily_json -> 'daily' -> 'uv_index_max'                ->> idx)::numeric       as uv_index_max,
    (daily_json -> 'daily' -> 'visibility_max'              ->> idx)::numeric       as visibility_max_m,
    (daily_json -> 'daily' -> 'visibility_min'              ->> idx)::numeric       as visibility_min_m,
    (daily_json -> 'daily' -> 'visibility_mean'             ->> idx)::numeric       as visibility_mean_m,
    (daily_json -> 'daily' -> 'cloud_cover_max'             ->> idx)::int           as cloud_cover_max_pct,
    (daily_json -> 'daily' -> 'cloud_cover_min'             ->> idx)::int           as cloud_cover_min_pct,
    (daily_json -> 'daily' -> 'cloud_cover_mean'            ->> idx)::int           as cloud_cover_mean_pct,
    (daily_json -> 'daily' -> 'dew_point_2m_max'            ->> idx)::numeric       as dew_point_2m_max_celsius,
    (daily_json -> 'daily' -> 'dew_point_2m_min'            ->> idx)::numeric       as dew_point_2m_min_celsius,
    (daily_json -> 'daily' -> 'dew_point_2m_mean'           ->> idx)::numeric       as dew_point_2m_mean_celsius,
    (daily_json -> 'daily' -> 'daylight_duration'           ->> idx)::numeric       as daylight_duration_seconds,
    (daily_json -> 'daily' -> 'precipitation_sum'           ->> idx)::numeric       as precipitation_sum_mm,
    (daily_json -> 'daily' -> 'precipitation_hours'         ->> idx)::numeric       as precipitation_hours,
    (daily_json -> 'daily' -> 'precipitation_probability_max'  ->> idx)::int        as precipitation_probability_max_pct,
    (daily_json -> 'daily' -> 'precipitation_probability_min'  ->> idx)::int        as precipitation_probability_min_pct,
    (daily_json -> 'daily' -> 'precipitation_probability_mean' ->> idx)::int        as precipitation_probability_mean_pct,
    (daily_json -> 'daily' -> 'sunshine_duration'           ->> idx)::numeric       as sunshine_duration_seconds,
    (daily_json -> 'daily' -> 'temperature_2m_max'          ->> idx)::numeric       as temperature_2m_max_celsius,
    (daily_json -> 'daily' -> 'temperature_2m_min'          ->> idx)::numeric       as temperature_2m_min_celsius,
    (daily_json -> 'daily' -> 'temperature_2m_mean'         ->> idx)::numeric       as temperature_2m_mean_celsius,
    (daily_json -> 'daily' -> 'apparent_temperature_max'    ->> idx)::numeric       as apparent_temperature_max_celsius,
    (daily_json -> 'daily' -> 'apparent_temperature_min'    ->> idx)::numeric       as apparent_temperature_min_celsius,
    (daily_json -> 'daily' -> 'apparent_temperature_mean'   ->> idx)::numeric       as apparent_temperature_mean_celsius,
    (daily_json -> 'daily' -> 'wind_gusts_10m_max'          ->> idx)::numeric       as wind_gusts_10m_max_kmh,
    (daily_json -> 'daily' -> 'wind_gusts_10m_min'          ->> idx)::numeric       as wind_gusts_10m_min_kmh,
    (daily_json -> 'daily' -> 'wind_gusts_10m_mean'         ->> idx)::numeric       as wind_gusts_10m_mean_kmh,
    (daily_json -> 'daily' -> 'wind_speed_10m_max'          ->> idx)::numeric       as wind_speed_10m_max_kmh,
    (daily_json -> 'daily' -> 'wind_speed_10m_min'          ->> idx)::numeric       as wind_speed_10m_min_kmh,
    (daily_json -> 'daily' -> 'wind_speed_10m_mean'         ->> idx)::numeric       as wind_speed_10m_mean_kmh,
    (daily_json -> 'daily' -> 'wind_direction_10m_dominant' ->> idx)::int           as wind_direction_10m_dominant,
    (daily_json -> 'daily' -> 'surface_pressure_max'        ->> idx)::numeric       as surface_pressure_max_hpa,
    (daily_json -> 'daily' -> 'surface_pressure_min'        ->> idx)::numeric       as surface_pressure_min_hpa,
    (daily_json -> 'daily' -> 'surface_pressure_mean'       ->> idx)::numeric       as surface_pressure_mean_hpa,
    (daily_json -> 'daily' -> 'relative_humidity_2m_max'    ->> idx)::int           as relative_humidity_2m_max_pct,
    (daily_json -> 'daily' -> 'relative_humidity_2m_min'    ->> idx)::int           as relative_humidity_2m_min_pct,
    (daily_json -> 'daily' -> 'relative_humidity_2m_mean'   ->> idx)::int           as relative_humidity_2m_mean_pct
from bronze.daily_stg
cross join lateral generate_series(
    0,
    jsonb_array_length(daily_json -> 'daily' -> 'time') - 1
) as idx
where create_date::date > coalesce(
    (select max(create_date::date) from silver.daily),
    '1900-01-01'::date
)
order by mountain_id, (daily_json -> 'daily' -> 'time' ->> idx)::date, create_date desc
on conflict (mountain_id, forecast_date)
do update set
    measured_at                         = excluded.measured_at,
    create_date                         = excluded.create_date,
    sunset                              = excluded.sunset,
    sunrise                             = excluded.sunrise,
    weather_code                        = excluded.weather_code,
    rain_sum_mm                         = excluded.rain_sum_mm,
    showers_sum_mm                      = excluded.showers_sum_mm,
    snowfall_sum_cm                     = excluded.snowfall_sum_cm,
    uv_index_max                        = excluded.uv_index_max,
    visibility_max_m                    = excluded.visibility_max_m,
    visibility_min_m                    = excluded.visibility_min_m,
    visibility_mean_m                   = excluded.visibility_mean_m,
    cloud_cover_max_pct                 = excluded.cloud_cover_max_pct,
    cloud_cover_min_pct                 = excluded.cloud_cover_min_pct,
    cloud_cover_mean_pct                = excluded.cloud_cover_mean_pct,
    dew_point_2m_max_celsius            = excluded.dew_point_2m_max_celsius,
    dew_point_2m_min_celsius            = excluded.dew_point_2m_min_celsius,
    dew_point_2m_mean_celsius           = excluded.dew_point_2m_mean_celsius,
    daylight_duration_seconds           = excluded.daylight_duration_seconds,
    precipitation_sum_mm                = excluded.precipitation_sum_mm,
    precipitation_hours                 = excluded.precipitation_hours,
    precipitation_probability_max_pct   = excluded.precipitation_probability_max_pct,
    precipitation_probability_min_pct   = excluded.precipitation_probability_min_pct,
    precipitation_probability_mean_pct  = excluded.precipitation_probability_mean_pct,
    sunshine_duration_seconds           = excluded.sunshine_duration_seconds,
    temperature_2m_max_celsius          = excluded.temperature_2m_max_celsius,
    temperature_2m_min_celsius          = excluded.temperature_2m_min_celsius,
    temperature_2m_mean_celsius         = excluded.temperature_2m_mean_celsius,
    apparent_temperature_max_celsius    = excluded.apparent_temperature_max_celsius,
    apparent_temperature_min_celsius    = excluded.apparent_temperature_min_celsius,
    apparent_temperature_mean_celsius   = excluded.apparent_temperature_mean_celsius,
    wind_gusts_10m_max_kmh              = excluded.wind_gusts_10m_max_kmh,
    wind_gusts_10m_min_kmh              = excluded.wind_gusts_10m_min_kmh,
    wind_gusts_10m_mean_kmh             = excluded.wind_gusts_10m_mean_kmh,
    wind_speed_10m_max_kmh              = excluded.wind_speed_10m_max_kmh,
    wind_speed_10m_min_kmh              = excluded.wind_speed_10m_min_kmh,
    wind_speed_10m_mean_kmh             = excluded.wind_speed_10m_mean_kmh,
    wind_direction_10m_dominant         = excluded.wind_direction_10m_dominant,
    surface_pressure_max_hpa            = excluded.surface_pressure_max_hpa,
    surface_pressure_min_hpa            = excluded.surface_pressure_min_hpa,
    surface_pressure_mean_hpa           = excluded.surface_pressure_mean_hpa,
    relative_humidity_2m_max_pct        = excluded.relative_humidity_2m_max_pct,
    relative_humidity_2m_min_pct        = excluded.relative_humidity_2m_min_pct,
    relative_humidity_2m_mean_pct       = excluded.relative_humidity_2m_mean_pct;